
services:
  postgres_server:
    container_name: 'postgres_container'
    image: postgres:16.0
    env_file:
      - .env.docker
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - habit_control

  app:
    container_name: fastapi_container
    build:
      context: .
      dockerfile: Dockerfile
    stop_signal: SIGTERM
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    environment:
      - TZ=Europe/Moscow
      - APP_PORT=8000
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    depends_on:
      - postgres_server
    command: ["./wait-for-it.sh", "postgres_server:5432", "--", "sh", "-c", "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"]
    networks:
      - habit_control
  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres_server
    depends_on:
      - postgres_server
    networks:
      - habit_control
volumes:
  postgres_data:

networks:
  habit_control:
    name: habit_control
    driver: bridge