"""first migrate

Revision ID: b61afe528a4f
Revises: 
Create Date: 2024-08-16 23:18:56.898578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b61afe528a4f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_control',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.String(length=25), nullable=False),
    sa.Column('fullname', sa.String(length=25), nullable=True),
    sa.Column('age', sa.String(length=3), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(length=25), nullable=True),
    sa.Column('city', sa.String(length=25), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('bot_user_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('habit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('habit_name', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.Column('reminder_time', sa.String(length=20), nullable=True),
    sa.Column('count_remained_day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habit_id'), 'habit', ['id'], unique=False)
    op.create_table('user_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_state_id'), 'user_state', ['id'], unique=False)
    op.create_table('habit_complected',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('habit_id', sa.Integer(), nullable=True),
    sa.Column('count_habit_complected', sa.Integer(), nullable=True),
    sa.Column('count_habit_not_complected', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habit.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habit_complected_id'), 'habit_complected', ['id'], unique=False)
    op.create_table('scheduler_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('habit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habit.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduler_jobs_id'), 'scheduler_jobs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduler_jobs_id'), table_name='scheduler_jobs')
    op.drop_table('scheduler_jobs')
    op.drop_index(op.f('ix_habit_complected_id'), table_name='habit_complected')
    op.drop_table('habit_complected')
    op.drop_index(op.f('ix_user_state_id'), table_name='user_state')
    op.drop_table('user_state')
    op.drop_index(op.f('ix_habit_id'), table_name='habit')
    op.drop_table('habit')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('message_control')
    # ### end Alembic commands ###
